"use strict";
let estaCovendo = false;
let idade = 18;
const nacionalidade = 'Brasileira';
const melhoresAmigos = ['Cauã', 'Guilherme'];
const tecnologiasWeb = ['HTML', 'CSS', 'JavaScript'];
const lista = ['Matheus', true, 18];
let idadeJuliana = 15;
idadeJuliana = '15 anos';
let dadosDaApi;
dadosDaApi = 14;
dadosDaApi = true;
dadosDaApi = 'Matheus e Juliana';
